name: frontend
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  csv: ^6.0.0
  davi: ^4.0.1
  file_saver: ^0.3.1
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_web_plugins:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.0
  hive_flutter: ^1.1.0
  http: ^1.2.1
  intl: ^0.20.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#333333"
    theme_color: "#D90428"

flutter_native_splash:
  color: "#333333"
  image: assets/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
